Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - a
    - b

Style/ExpandPathArguments:
  Enabled: false

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/SymbolArray:
  EnforcedStyle: brackets
